// Generated by Haxe 4.1.5

#pragma warning disable 109, 114, 219, 429, 168, 162
public class FileManager : global::haxe.lang.HxObject {
	
	static FileManager() {
		global::FileManager.content = "";
		global::FileManager.ext = "";
	}
	
	
	public FileManager(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public FileManager() {
		global::FileManager.__hx_ctor__FileManager(this);
	}
	
	
	protected static void __hx_ctor__FileManager(global::FileManager __hx_this) {
	}
	
	
	public static string content;
	
	public static string ext;
	
	public static void setType(global::FileType type) {
		unchecked {
			switch (type._hx_index) {
				case 0:
				{
					global::FileManager.ext = ".cec";
					break;
				}
				
				
				case 1:
				{
					global::FileManager.ext = ".lua";
					break;
				}
				
				
				case 2:
				{
					global::FileManager.ext = ".asm";
					break;
				}
				
				
			}
			
		}
	}
	
	
	public static void append(string text) {
		{
			System.Type __temp_dynop1 = typeof(global::FileManager);
			global::FileManager.content = global::haxe.lang.Runtime.concat(global::FileManager.content, text);
		}
		
	}
	
	
	public static void save(string path, string name) {
		global::sys.io.File.saveContent(global::haxe.io.Path.@join(new global::Array<string>(new string[]{path, global::haxe.lang.Runtime.concat(name, global::FileManager.ext)})), global::FileManager.content);
		global::System.Console.WriteLine(((object) (global::haxe.lang.Runtime.concat("File saved to ", global::haxe.io.Path.@join(new global::Array<string>(new string[]{path, global::haxe.lang.Runtime.concat(name, global::FileManager.ext)})))) ));
	}
	
	
}



#pragma warning disable 109, 114, 219, 429, 168, 162
public class FileType : global::haxe.lang.Enum {
	
	protected FileType(int index) : base(index) {
	}
	
	
	public static readonly global::FileType CELERITE = new global::FileType_CELERITE();
	
	public static readonly global::FileType LUA = new global::FileType_LUA();
	
	public static readonly global::FileType ASSEMBLY = new global::FileType_ASSEMBLY();
	
}



#pragma warning disable 109, 114, 219, 429, 168, 162
public sealed class FileType_CELERITE : global::FileType {
	
	public FileType_CELERITE() : base(0) {
	}
	
	
	public override string getTag() {
		return "CELERITE";
	}
	
	
}



#pragma warning disable 109, 114, 219, 429, 168, 162
public sealed class FileType_LUA : global::FileType {
	
	public FileType_LUA() : base(1) {
	}
	
	
	public override string getTag() {
		return "LUA";
	}
	
	
}



#pragma warning disable 109, 114, 219, 429, 168, 162
public sealed class FileType_ASSEMBLY : global::FileType {
	
	public FileType_ASSEMBLY() : base(2) {
	}
	
	
	public override string getTag() {
		return "ASSEMBLY";
	}
	
	
}


